# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from grasp_pointcloud/VolumeParams.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class VolumeParams(genpy.Message):
  _md5sum = "f7eed6e54339e802bc0a68ef8afe8226"
  _type = "grasp_pointcloud/VolumeParams"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool reverse
float64 x
float64 y
float64 z
float64 rotate_angle
float64 volume
float64 width"""
  __slots__ = ['reverse','x','y','z','rotate_angle','volume','width']
  _slot_types = ['bool','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       reverse,x,y,z,rotate_angle,volume,width

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VolumeParams, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.reverse is None:
        self.reverse = False
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.z is None:
        self.z = 0.
      if self.rotate_angle is None:
        self.rotate_angle = 0.
      if self.volume is None:
        self.volume = 0.
      if self.width is None:
        self.width = 0.
    else:
      self.reverse = False
      self.x = 0.
      self.y = 0.
      self.z = 0.
      self.rotate_angle = 0.
      self.volume = 0.
      self.width = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B6d().pack(_x.reverse, _x.x, _x.y, _x.z, _x.rotate_angle, _x.volume, _x.width))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 49
      (_x.reverse, _x.x, _x.y, _x.z, _x.rotate_angle, _x.volume, _x.width,) = _get_struct_B6d().unpack(str[start:end])
      self.reverse = bool(self.reverse)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B6d().pack(_x.reverse, _x.x, _x.y, _x.z, _x.rotate_angle, _x.volume, _x.width))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 49
      (_x.reverse, _x.x, _x.y, _x.z, _x.rotate_angle, _x.volume, _x.width,) = _get_struct_B6d().unpack(str[start:end])
      self.reverse = bool(self.reverse)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B6d = None
def _get_struct_B6d():
    global _struct_B6d
    if _struct_B6d is None:
        _struct_B6d = struct.Struct("<B6d")
    return _struct_B6d
