// Generated by gencpp from file grasp_pointcloud/AdjustParams.msg
// DO NOT EDIT!


#ifndef GRASP_POINTCLOUD_MESSAGE_ADJUSTPARAMS_H
#define GRASP_POINTCLOUD_MESSAGE_ADJUSTPARAMS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace grasp_pointcloud
{
template <class ContainerAllocator>
struct AdjustParams_
{
  typedef AdjustParams_<ContainerAllocator> Type;

  AdjustParams_()
    : y(0.0)
    , z(0.0)
    , y_rotate_angle(0.0)
    , z_rotate_angle(0.0)  {
    }
  AdjustParams_(const ContainerAllocator& _alloc)
    : y(0.0)
    , z(0.0)
    , y_rotate_angle(0.0)
    , z_rotate_angle(0.0)  {
  (void)_alloc;
    }



   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _y_rotate_angle_type;
  _y_rotate_angle_type y_rotate_angle;

   typedef double _z_rotate_angle_type;
  _z_rotate_angle_type z_rotate_angle;





  typedef boost::shared_ptr< ::grasp_pointcloud::AdjustParams_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grasp_pointcloud::AdjustParams_<ContainerAllocator> const> ConstPtr;

}; // struct AdjustParams_

typedef ::grasp_pointcloud::AdjustParams_<std::allocator<void> > AdjustParams;

typedef boost::shared_ptr< ::grasp_pointcloud::AdjustParams > AdjustParamsPtr;
typedef boost::shared_ptr< ::grasp_pointcloud::AdjustParams const> AdjustParamsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grasp_pointcloud::AdjustParams_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grasp_pointcloud::AdjustParams_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace grasp_pointcloud

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'grasp_pointcloud': ['/home/jay/grasp_ws/src/grasp_pointcloud/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::grasp_pointcloud::AdjustParams_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grasp_pointcloud::AdjustParams_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grasp_pointcloud::AdjustParams_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grasp_pointcloud::AdjustParams_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasp_pointcloud::AdjustParams_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasp_pointcloud::AdjustParams_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grasp_pointcloud::AdjustParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57feed5981af266697038b66e7af4ff4";
  }

  static const char* value(const ::grasp_pointcloud::AdjustParams_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57feed5981af2666ULL;
  static const uint64_t static_value2 = 0x97038b66e7af4ff4ULL;
};

template<class ContainerAllocator>
struct DataType< ::grasp_pointcloud::AdjustParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grasp_pointcloud/AdjustParams";
  }

  static const char* value(const ::grasp_pointcloud::AdjustParams_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grasp_pointcloud::AdjustParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 y\n\
float64 z\n\
float64 y_rotate_angle\n\
float64 z_rotate_angle\n\
";
  }

  static const char* value(const ::grasp_pointcloud::AdjustParams_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grasp_pointcloud::AdjustParams_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.y_rotate_angle);
      stream.next(m.z_rotate_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AdjustParams_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grasp_pointcloud::AdjustParams_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grasp_pointcloud::AdjustParams_<ContainerAllocator>& v)
  {
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "y_rotate_angle: ";
    Printer<double>::stream(s, indent + "  ", v.y_rotate_angle);
    s << indent << "z_rotate_angle: ";
    Printer<double>::stream(s, indent + "  ", v.z_rotate_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASP_POINTCLOUD_MESSAGE_ADJUSTPARAMS_H
