// Generated by gencpp from file grasp_pointcloud/PointBoundingBox.msg
// DO NOT EDIT!


#ifndef GRASP_POINTCLOUD_MESSAGE_POINTBOUNDINGBOX_H
#define GRASP_POINTCLOUD_MESSAGE_POINTBOUNDINGBOX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace grasp_pointcloud
{
template <class ContainerAllocator>
struct PointBoundingBox_
{
  typedef PointBoundingBox_<ContainerAllocator> Type;

  PointBoundingBox_()
    : xmin(0.0)
    , ymin(0.0)
    , xmax(0.0)
    , ymax(0.0)  {
    }
  PointBoundingBox_(const ContainerAllocator& _alloc)
    : xmin(0.0)
    , ymin(0.0)
    , xmax(0.0)
    , ymax(0.0)  {
  (void)_alloc;
    }



   typedef double _xmin_type;
  _xmin_type xmin;

   typedef double _ymin_type;
  _ymin_type ymin;

   typedef double _xmax_type;
  _xmax_type xmax;

   typedef double _ymax_type;
  _ymax_type ymax;





  typedef boost::shared_ptr< ::grasp_pointcloud::PointBoundingBox_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grasp_pointcloud::PointBoundingBox_<ContainerAllocator> const> ConstPtr;

}; // struct PointBoundingBox_

typedef ::grasp_pointcloud::PointBoundingBox_<std::allocator<void> > PointBoundingBox;

typedef boost::shared_ptr< ::grasp_pointcloud::PointBoundingBox > PointBoundingBoxPtr;
typedef boost::shared_ptr< ::grasp_pointcloud::PointBoundingBox const> PointBoundingBoxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grasp_pointcloud::PointBoundingBox_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grasp_pointcloud::PointBoundingBox_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace grasp_pointcloud

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'grasp_pointcloud': ['/home/jay/grasp_ws/src/grasp_pointcloud/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::grasp_pointcloud::PointBoundingBox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grasp_pointcloud::PointBoundingBox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grasp_pointcloud::PointBoundingBox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grasp_pointcloud::PointBoundingBox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasp_pointcloud::PointBoundingBox_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasp_pointcloud::PointBoundingBox_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grasp_pointcloud::PointBoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2da0e8eb269cd8cc187fb4c7d113d543";
  }

  static const char* value(const ::grasp_pointcloud::PointBoundingBox_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2da0e8eb269cd8ccULL;
  static const uint64_t static_value2 = 0x187fb4c7d113d543ULL;
};

template<class ContainerAllocator>
struct DataType< ::grasp_pointcloud::PointBoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grasp_pointcloud/PointBoundingBox";
  }

  static const char* value(const ::grasp_pointcloud::PointBoundingBox_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grasp_pointcloud::PointBoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 xmin\n\
float64 ymin\n\
float64 xmax\n\
float64 ymax\n\
";
  }

  static const char* value(const ::grasp_pointcloud::PointBoundingBox_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grasp_pointcloud::PointBoundingBox_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.xmin);
      stream.next(m.ymin);
      stream.next(m.xmax);
      stream.next(m.ymax);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PointBoundingBox_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grasp_pointcloud::PointBoundingBox_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grasp_pointcloud::PointBoundingBox_<ContainerAllocator>& v)
  {
    s << indent << "xmin: ";
    Printer<double>::stream(s, indent + "  ", v.xmin);
    s << indent << "ymin: ";
    Printer<double>::stream(s, indent + "  ", v.ymin);
    s << indent << "xmax: ";
    Printer<double>::stream(s, indent + "  ", v.xmax);
    s << indent << "ymax: ";
    Printer<double>::stream(s, indent + "  ", v.ymax);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASP_POINTCLOUD_MESSAGE_POINTBOUNDINGBOX_H
