// Generated by gencpp from file grasp_pointcloud/VolumeParams.msg
// DO NOT EDIT!


#ifndef GRASP_POINTCLOUD_MESSAGE_VOLUMEPARAMS_H
#define GRASP_POINTCLOUD_MESSAGE_VOLUMEPARAMS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace grasp_pointcloud
{
template <class ContainerAllocator>
struct VolumeParams_
{
  typedef VolumeParams_<ContainerAllocator> Type;

  VolumeParams_()
    : reverse(false)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , rotate_angle(0.0)
    , volume(0.0)
    , width(0.0)  {
    }
  VolumeParams_(const ContainerAllocator& _alloc)
    : reverse(false)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , rotate_angle(0.0)
    , volume(0.0)
    , width(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _reverse_type;
  _reverse_type reverse;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _rotate_angle_type;
  _rotate_angle_type rotate_angle;

   typedef double _volume_type;
  _volume_type volume;

   typedef double _width_type;
  _width_type width;





  typedef boost::shared_ptr< ::grasp_pointcloud::VolumeParams_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grasp_pointcloud::VolumeParams_<ContainerAllocator> const> ConstPtr;

}; // struct VolumeParams_

typedef ::grasp_pointcloud::VolumeParams_<std::allocator<void> > VolumeParams;

typedef boost::shared_ptr< ::grasp_pointcloud::VolumeParams > VolumeParamsPtr;
typedef boost::shared_ptr< ::grasp_pointcloud::VolumeParams const> VolumeParamsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grasp_pointcloud::VolumeParams_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grasp_pointcloud::VolumeParams_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace grasp_pointcloud

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'grasp_pointcloud': ['/home/jay/grasp_ws/src/grasp_pointcloud/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::grasp_pointcloud::VolumeParams_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grasp_pointcloud::VolumeParams_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grasp_pointcloud::VolumeParams_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grasp_pointcloud::VolumeParams_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasp_pointcloud::VolumeParams_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasp_pointcloud::VolumeParams_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grasp_pointcloud::VolumeParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f7eed6e54339e802bc0a68ef8afe8226";
  }

  static const char* value(const ::grasp_pointcloud::VolumeParams_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf7eed6e54339e802ULL;
  static const uint64_t static_value2 = 0xbc0a68ef8afe8226ULL;
};

template<class ContainerAllocator>
struct DataType< ::grasp_pointcloud::VolumeParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grasp_pointcloud/VolumeParams";
  }

  static const char* value(const ::grasp_pointcloud::VolumeParams_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grasp_pointcloud::VolumeParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool reverse\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 rotate_angle\n\
float64 volume\n\
float64 width\n\
";
  }

  static const char* value(const ::grasp_pointcloud::VolumeParams_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grasp_pointcloud::VolumeParams_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reverse);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.rotate_angle);
      stream.next(m.volume);
      stream.next(m.width);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VolumeParams_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grasp_pointcloud::VolumeParams_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grasp_pointcloud::VolumeParams_<ContainerAllocator>& v)
  {
    s << indent << "reverse: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reverse);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "rotate_angle: ";
    Printer<double>::stream(s, indent + "  ", v.rotate_angle);
    s << indent << "volume: ";
    Printer<double>::stream(s, indent + "  ", v.volume);
    s << indent << "width: ";
    Printer<double>::stream(s, indent + "  ", v.width);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASP_POINTCLOUD_MESSAGE_VOLUMEPARAMS_H
